# default: true
replaceLogoAndEdition = true
# default: 30
logoTopSpace = 6
# default: 256
logoScreenWidth = 192
# default: 44
logoScreenHeight = 89
# default: 256
logoTextureWidth = 192
# default: 64
logoTextureHeight = 89
# default: -7
editionTopSpace = 0
# default: 128
editionScreenWidth = 128
# default: 14
editionScreenHeight = 14
# default: 128
editionTextureWidth = 128
# default: 16
editionTextureHeight = 16
# default: 123
splashCenterOffset = 110
# default: 69
splashHeight = 75
# Angle in radians
# default: -0.34906584
splashRotation = -0.34906584
# default: false
replaceLoadingLogo = false
